### PR TITLE
feat: add alert support to linux

### PR DESCRIPTION
**Pull request by jasonraimondi**
requires vlc as a dependency for linux

Tested on:

```
OS: Pop!_OS 20.10 x86_64 
Host: Lemur Pro lemp9 
Kernel: 5.8.0-7630-generic 
Shell: zsh 5.8 
Resolution: 1920x1080 
CPU: Intel i7-10510U (8) @ 4.900GHz 
GPU: Intel UHD Graphics 
Memory: 7027MiB / 15881MiB 
```

```
~/C/p/get-my-ps5 ❯❯❯ vlc --version
VLC media player 3.0.11.1 Vetinari (revision 3.0.11.1-0-g52483f3ca2)
VLC version 3.0.11.1 Vetinari (3.0.11.1-0-g52483f3ca2)
Compiled by buildd on lgw01-amd64-035.buildd (Sep 22 2020 21:11:26)
Compiler: gcc version 10.2.0 (Ubuntu 10.2.0-9ubuntu2)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public License;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.
```

### CODE REVIEW

**Comment by camtheperson** [comment]
@jasonraimondi If you'd still like credit for your PR, please sync with the RC branch and resolve your conflicts. I'll give you another hour or two, but otherwise I'll just add them to the RC branch myself. Thanks!

**Review by camtheperson — CHANGES_REQUESTED** [review]
Resolve merge conflicts.

**Review by camtheperson — APPROVED** [review]

**Comment by jasonraimondi** [comment]
@camtheperson conflicts should be resolved and good to go, if I am missing anything, feel free to make any adjustments without needing to wait for me (or you can wait for me, either way, all good).

**Comment by ReillyBrogan** [comment]
@jasonraimondi Do you have any objection to using `xdg-open` as the command line instead of `nvlc` (`xdg-open` opens the mp3 in whatever is currently set as the default handler for mp3 files, duplicating the behavior of the other OSs)?

**Comment by jasonraimondi** [comment]
Not at all, that is probably smarter. I could create a new pr but not for an hour or two. Feel free to go ahead without me if you're up to it.

**Comment by ReillyBrogan** [comment]
@jasonraimondi #50

**Pull request merged**
